theme: jekyll-theme-architect
code: "<div id="diy_right_menu">
    <ul>
        <li style="list-style: none;text-align: center;">目录页</li>
        <li><a href="/0210921">制作canvas游戏</a></li>
    </ul>
</div>
<style>
#diy_right_menu {
                opacity: 0.5;
                position: fixed;
                right: 2%;
                top: 2%;
                width: 20em;
                margin-top: 1em;
                background-color: black;
                padding: 1em;
                border-radius: 0;
                transition: 0.6s ease-in-out;
                color: white;
                border-radius: 5px;
    overflow-y: auto;
max-height: 450px;
            }
            
            #diy_right_menu:hover {
                color: white;
                right: 2%;
                top: 2%;
                border-radius: 10px;
                opacity: 1.3;
                box-shadow: 0 10px 20px rgba(0, 0, 0, 0.5);
                transition: 0.4s ease-in-out;
            }
            
            #diy_right_menu a {
                transition: 0.4s ease-in-out;
            }
            
            #diy_right_menu a:hover {
                transition: 0.4s ease-in-out;
            }
</style>"
